apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: 857360183365.dkr.ecr.ap-northeast-3.amazonaws.com/sesac-jhj-hello-world-app:v1
        ports:
        - containerPort: 3000
      